import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Fotos() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Paz Gutierrez Espin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Paz Gutierrez- Fotos
      </main>

    </div>
  )
}
